//USERS//
export const LOGIN_USER = "LOGIN_USER"

//SANDWICHES//
export const GET_SANDWICHES = "GET_SANDWICHES"
export const GET_SANDWICH = "GET_SANDWICH"
export const SANDWICH_CLICK = "SANDWICH_CLICK"

//DELIS//
export const GET_DELIS = "GET_DELIS"
export const CURRENT_DELI = "CURRENT_DELI"
export const GET_DELI ="GET_DELI"

//FILTERS//
export const DELI_FILTER = "DELI_FILTER"
export const SANDWICH_FILTER = "SANDWICH_FILTER"

//REVIEWS//
export const GET_REVIEWS = "GET_REVIEWS"
export const REVIEW_EDIT_CLICK = "REVIEW_EDIT_CLICK"
export const REVIEW_CLICK = "REVIEW_CLICK"
export const RENDER_REVIEW = "RENDER_REVIEW"
export const POST_REVIEW = "POST_REVIEW"
export const PATCH_REVIEW = "PATCH_REVIEW"
export const REVIEW_FORM = "REVIEW_FORM"
